### ISSUE TITLE
Overlapping allowed even though allowOverlap is false

### ISSUE THREAD

**Issue by sergiotbh** [ptomasroos/react-native-multi-slider#105]
☑️ I have searched [existing issues]
☑️ I am using the [latest multi slider version]

When I set **allowOverlap** to **false**, it works as expected, but when I reload the screen, it allows me to overlap both cursors again. It also happens when I don't set **allowOverlap**

This is on **iOS**, haven't tested on Android

```
onValuesChange(values){
        this.setState({limitesDensidad: values})
    }

                  <MultiSlider
                        ref={e => this.slider = e}
                        selectedStyle={{
                            backgroundColor: globals.colors.tealBlueDark,
                        }}
                        unselectedStyle={{
                            backgroundColor: 'lightgrey',
                        }}
                        values={[this.props.limitesDensidad[0],this.props.limitesDensidad[1]]}
                        onValuesChange={(values) => {
                                 this.props.onValuesChange(values)
                        }}
                        containerStyle={{
                            height: 80,
                        }}
                        trackStyle={{
                            height: 3,
                        }}
                        touchDimensions={{
                            height: 40,
                            width: 40,
                            borderRadius: 20,
                            slipDisplacement: 40,
                        }}
                        
                        customMarker={SliderDot}
                        sliderLength={this.state.sliderLength}
                        min={25}
                        max={29}
                        allowOverlap={false}
                        snapped={true}
                    />
```
Showing both cursors:
![screen shot 2019-01-02 at 15 36 07](https://user-images.githubusercontent.com/32079020/50613914-d1469500-0ea4-11e9-9d15-2f35ee64687b.png)

Now overlapped, even though allowOverlap is **false** (also happens when I don't set allowOverlap):
![screen shot 2019-01-02 at 15 36 16](https://user-images.githubusercontent.com/32079020/50613901-c55ad300-0ea4-11e9-9c6e-8767d2cb4f6d.png)

**Comment by sergiotbh** [comment]
(Edited out some experimental code on a failed attempt to find a workaround)

**Comment by CyxouD** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/17162008/52441383-1ce60180-2b29-11e9-8f1f-605247849503.png">
This happens because of this calculation, if `this.props.sliderLength` or `this.optionsArray.length` are quite large and close to each other, then this value is quite small.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/17162008/52441474-574f9e80-2b29-11e9-9931-d01951c5ea86.png">
This value then used for calculation based on `this.props.allowOverlap`. As you can see, if it is small and there are quite a lot of values, markers will still overlap. 

My suggestion would be to have prop `stepLength`, which will override it's calculation

**Comment by ptomasroos** [comment]
Thanks @CyxouD

Have you tried with snapped={true} and it still occurs?
Can you create a repo for me in order to reproduce this and I will take a look at it

**Comment by abhishkekalia** [comment]
+1

**Comment by syedtehrimabbas** [comment]
@sergiotbh 
Hi mate,
please use isMarkersSeparated =false
**isMarkersSeparated={false}
allowOverlap={false}
snapped={true}**
Hope fully it will fix your issue.

![2u8dbk](https://user-images.githubusercontent.com/26393867/53156196-a2b18480-35e0-11e9-8387-2c823229649a.gif)

**Comment by luco** [comment]
@syedtehrimabbas Your fix doesn't work:

![image](https://user-images.githubusercontent.com/246373/60285720-8736ed00-98e4-11e9-94ff-24f429fd08a5.png)

**Comment by RobinCsl** [comment]
@ptomasroos, we added this functionality in a fork of this repository (see https://github.com/kiwicom/react-native-multi-slider/commits/master).
In the package depending on it (`@kiwicom/universal-components`), we're targeting the GitHub URL to the repo... and this seems to trigger a weird bug in some GitLab CI pipelines with `yarn install`... So I would much rather use `@ptomasroos/react-native-multi-slider` instead of our fork.

Since it seems this issue is still open, would you consider integrating these changes here and publish a new version of the package to NPM?

We also used it in a web environment (see https://kiwicom-universal-components.netlify.com/?selectedKind=Slider&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel to see it in action!), so we added some build step to make sure the JavaScript is transpiled.

e.g. 
<img width="157" alt="Screenshot 2019-07-09 at 17 04 23" src="https://user-images.githubusercontent.com/22741774/60899942-a7af6180-a26b-11e9-920d-bce3f67a1d52.png">


Let me know if that's something you'd like and if I could be of any help!
Thanks a lot!

**Comment by ptomasroos** [comment]
Of course! Would be great to have a PR for this.

**Comment by AmauryLiet** [comment]
Seems like `stepLength` calculation is wrong, which cause the bug.

For reference [the calculation](../blob/94fb574d507e86a41fb44dec358bbcd45cf20dec/MultiSlider.js#L54):
```
    this.optionsArray =
      this.props.optionsArray ||
      createArray(this.props.min, this.props.max, this.props.step);
    this.stepLength = this.props.sliderLength / this.optionsArray.length;
```


If your slider goes from, let's say, 0 to 10:
- `this.optionsArray = [0, 1, ... 10];` => its length is 11
- however, `this.props.sliderLength` should only be divided by 10 (representing the 10 sections `0-1`, `1-2`, ..., `9-10`)

The fix is then simply to replace L56 by
`    this.stepLength = this.props.sliderLength / (this.optionsArray.length - 1);`

I opened a PR: #209
