### ISSUE TITLE
Outdated version for npm

### ISSUE THREAD

**Issue by piotrponikowski** [ptomasroos/react-native-multi-slider#140]
Hello, 
version bublished to npm looks outdated:
https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider
https://www.npmjs.com/package/@types/ptomasroos__react-native-multi-slider

For example it doesn't contain property 'minMarkerOverlapDistance', which is available on github.

Are there any chances to publish the newest version to npm?

**Comment by munafmohammed** [comment]
Yes, please publish the new version on npm. I am waiting too.

**Comment by ptomasroos** [comment]
Hi!

What happened was that I was about to change namespace because of the conflict with the upcoming gradle 5 release and then my assingment on react-native projects got removed.

I will do my best to do this during the week. But we will need to change the package name.

Sorry for not being more active, and thanks for the reminder!

**Comment by ptomasroos** [comment]
All right, I'll publish a update shortly now that I've got some time to work with the multi slider again! 🎉and help from the community!

**Comment by baconcheese113** [comment]
@ptomasroos Will you be publishing to npm with the same package name?

**Comment by ptomasroos** [comment]
Yes! Need to fix the regression first

**Comment by ptomasroos** [comment]
Will fix that during tomorrow

**Comment by glburgess** [comment]
I want to thank you tending to this! I use it a lot and please know how much I genuinely appreciate the work you and others have done!!
