### ISSUE TITLE
Allow out of range numbers 

### ISSUE THREAD

**Issue by brianlaw033** [ptomasroos/react-native-multi-slider#43]
How can I handle cases when one of the values are out of range?
like the slider's min: 0 max: 100
but the values[1] is 1000

**Comment by ptomasroos** [comment]
Can you create a example repo with the example in Basic? And I could take a look at it

**Comment by brianlaw033** [comment]
not really complicated

```
<TextInput
    style={{height: 40, borderColor: 'gray', borderWidth: 1}}
    keyboardType={'numeric'}
    value={this.state.priceMax}
    onChangeText={(num) => this.setState({priceMax: num})}
/>
<MultiSlider
     values={[this.state.priceMin, this.state.priceMax]}
     sliderLength={280}
     onValuesChange={(values) => this.setState({priceMin: values[0], priceMax: values[1]})}
     min={0}
     max={5000}
     step={100}
     snapped
/>
```

I want to accept some extreme cases where when the range in the slider is not enough
so users can enter the maximum price, but wont affect the slidebar (remains on the end of right hand side)

**Comment by ptomasroos** [comment]
All right I started looking into this @brianlaw033 . Where would you like the position to be in the case of a value of 1000? At the 1000 spot? What happens when the user drags the slider, shall it go from 1000-> 99 in that case? I'm just trying to understand the use-case. We can of course make sure the component doesn't error but I'm not sure the use-case.
