### ISSUE TITLE
Values on multislider always starts at [0, 0] with redux.

### ISSUE THREAD

**Issue by meurling** [ptomasroos/react-native-multi-slider#48]
Hello!
So my problem is that my markers always start at 0, even though my initial state in my reducer is [18, 25].
Anyone knows how to solve this?

My code looks like this:
```
class multiSlider extends PureComponent{
    render(){
        const {
            _setSliderState,
            _setSliderValue,
            _sliderState,
            _sliderValue
        } = this.props;
        return(
            <View style={{alignItems: "center", justifyContent: "center"}} >
            
                <MultiSlider
                    values={[_sliderValue[0], _sliderValue[1]]}
                    sliderLength={width - 40}
                    min={18}
                    max={55}
                    onValuesChange={(values) => _setSliderValue(values)}
                    selectedStyle={{
                        backgroundColor: 'rgb(164, 39, 141)',
                    }}
                    trackStyle={{
                        height:5,
                    }}
                    touchDimensions={{
                        height: 200,
                        width: 40,
                        borderRadius: 30,
                        slipDisplacement: 40,
                    }}
                    customMarker={CustomMarker}
                />
            </View>
        )
    }
}
```

**Comment by ptomasroos** [comment]
We use             values={[value1, value2]}
There is no issue with that at least from my knowledge. Are you sure you're input values in this case _sliderValue[0], _sliderValue[1] are having any correct values? Try log them or debug these values since its very likely that the issue is the connection to redux rather than something in the component.

We for a fact use redux with the multislider succesfully since at least 8 months ago

**Comment by IlifilzaRusli** [comment]
@ptomasroos  I'm using values [31317, 425300] for the MultiSlider. But both start at [0,0]. values[11000, 678900] works though. Do you know why?
